### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by loadedice**
Howdy,

I was reading the documentation the other day and spotted a few typos!

I suspected there are more than just the ones I spotted, so I ran it through aspell and fixed a few more.

### CODE REVIEW

**Review by zyzek — APPROVED** [review]

**Comment by zyzek** [comment]
:+1:

**Comment by ricmoo** [comment]
Oh, aspell is probably still a bit away. :)

I will be merging typo fixes on my next update to the docs, I just haven’t had time, but will make sure I get to this sooner than later. :)

**Comment by ricmoo** [comment]
(unless someone wants to write an npm spell check that can read RST for me :))

**Comment by ricmoo** [comment]
Also, huge thanks for this PR. :)

**Comment by ricmoo** [comment]
Merged and published!

Thanks. :)

**Pull request merged**
